//
//  HomePresenterTests.swift
//  NagwaTask
//
//  Created by Nrmeen Tomoum on 12/29/18.
//  Copyright (c) 2018 Nagwa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NagwaTask
import XCTest

class HomePresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: HomePresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupHomePresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupHomePresenter()
  {
    sut = HomePresenter()
  }
  
  // MARK: Test doubles
  
  class HomeDisplayLogicSpy: HomeDisplayLogic
  {
    func displayIndecator() {
        
    }
    
    func stopIndecator() {
        
    }
    
    func createAlert(title: String, subTitle: String) {
        displaySomethingCalled = true
    }
    
    func displayListOfRepositories(viewModel: [Home.Repository.ViewModel]) {
    
    }
    
   
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: Home.Repository.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
 
   
  func testPresentSomething()
  {
    // Given
    let spy = HomeDisplayLogicSpy()
    sut.viewController = spy
   // let response = Home.Repository.Response()
    
    // When
    sut.presentAlertMessage(message: "ServerDown")
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
