//
//  HomeInteractorTests.swift
//  NagwaTask
//
//  Created by Nrmeen Tomoum on 12/29/18.
//  Copyright (c) 2018 Nagwa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NagwaTask
import XCTest

class HomeInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: HomeInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupHomeInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupHomeInteractor()
  {
    sut = HomeInteractor()
  }
  
  // MARK: Test doubles
  
  class HomePresentationLogicSpy: HomePresentationLogic
  {
    func presentStopLoader() {
        <#code#>
    }
    
    func presentLoader() {
        <#code#>
    }
    
    func presentAlertMessage(message: String) {
        <#code#>
    }
    
    func presentListOfRepositories(response: [Home.Repository.Response]) {
        
    }
    
    var presentSomethingCalled = false
    
    func presentSomething(response: Home.Repository.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = HomePresentationLogicSpy()
    sut.presenter = spy
    let request = Home.Repository.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
