//
//  HomeInteractorTests.swift
//  NagwaTask
//
//  Created by Nrmeen Tomoum on 12/29/18.
//  Copyright (c) 2018 Nagwa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NagwaTask
import XCTest

class HomeInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: HomeInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupHomeInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupHomeInteractor()
  {
    sut = HomeInteractor()
  }
  
  // MARK: Test doubles
  
  class HomePresentationLogicSpy: HomePresentationLogic
  {
    var presentAlertMessageflag = false
    var presentStopLoaderflag = false
    var presentLoaderflag = false
    var presentListOfRepositoriesflag = false
    
    func presentStopLoader() {
        presentStopLoaderflag = true
    }
    
    func presentLoader() {
        presentLoaderflag = true
    }
    
    func presentAlertMessage(message: String) {
        presentAlertMessageflag = true
    }
    
    func presentListOfRepositories(response: [Home.Repository.Response]) {
        presentListOfRepositoriesflag = true
    }
    
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = HomePresentationLogicSpy()
    sut.presenter = spy
//    let request = Home.Repository.Request()
    
    // When
    sut.getRepositories(request: Home.Repository.Request(page: 1, size: 15), fromAPIOrCD: true)
    
    // Then
    XCTAssertTrue(spy.presentListOfRepositoriesflag, "doSomething(request:) should ask the presenter to format the result")
  }
}
